export const ARTICLES_FETCHED = "ARTICLES_FETCHED";
export const ARTICLES_FETCHING_LOADING = "ARTICLES_FETCHING_LOADING";
export const ARTICLES_FETCHING_ERROR = "ARTICLES_FETCHING_ERROR";

export const ARTICLE_FETCHED = "ARTICLE_FETCHED";
export const ARTICLE_FETCHING_LOADING = "ARTICLE_FETCHING_LOADING";
export const ARTICLE_FETCHING_ERROR = "ARTICLE_FETCHING_ERROR";
